sudo: required

services:
  - docker

env:
  COMPOSE_VERSION: 1.4.1

branches:
  only:
    - master
    - develop
    - hotfix
    - travis

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

script:
  - cd meta
  - docker-compose -f docker/slatwall-ci/docker-compose.yml up -d
  - docker ps
  - docker-machine ip
  - docker-machine url
  - docker-machine inspect
  - sleep 10
  - docker logs --tail=500 slatwallci_slatwallweb_1
  - docker exec -i -t slatwallci_slatwallweb_1 ant -f /var/www/meta/build.xml runUnitTests
